version: "3.9"

services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  server:
    build: ./Server
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      - PORT=5000
      - JWT_SECRET=Ujjwal@2004
      - JWT_EXPIRES_IN=1d
      - MONGO_URI=mongodb+srv://pathakujjwal0001_db_user:15djsYL0xipygKyM@cluster0.vpuejma.mongodb.net/fs_project?appName=Cluster0
      - TENANT_ROOT_DOMAIN=example.com
    ports:
      - "5000:5000"
    volumes:
      - ./Server:/app
      - server-node-modules:/app/node_modules

  client:
    build: ./client/vite-project
    restart: unless-stopped
    depends_on:
      - server
    environment:
      - VITE_API_URL=http://localhost:5000
    ports:
      - "5173:5173"
    volumes:
      - ./client/vite-project:/app
      - client-node-modules:/app/node_modules

volumes:
  mongo-data:
  server-node-modules:
  client-node-modules: